const SUPABASE_URL='https://cfyxcopixetvlvhjftxv.supabase.co';
const SUPABASE_KEY='sb_publishable_1qWG5IZvHmfEOADJwCGhFg_79aZgQDq';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
let session=null, ownerData=null, currentSchool=null, currentDetail=null, currentRole='owner';
function showStatus(el,msg,type=''){el.textContent=msg;el.className='status show'+(type?' '+type:'')}
function clearStatus(el){el.textContent='';el.className='status'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function authReady(){const {data}=await sb.auth.getSession();session=data.session;if(session){$('authWrap').classList.add('hidden');$('app').classList.remove('hidden');$('ownerEmail').textContent=session.user.email||'';$('profileMeta').textContent=session.user.email||'';await loadOwner();}}
$('login').onclick=async()=>{try{clearStatus($('authStatus'));const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<6)throw new Error('И-мэйл болон нууц үгээ зөв оруулна уу.');showStatus($('authStatus'),'Нэвтэрч байна…');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;session=data.session;await authReady()}catch(e){showStatus($('authStatus'),'Нэвтрэх алдаа: '+e.message,'err')}};
$('signup').onclick=async()=>{try{clearStatus($('authStatus'));const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<6)throw new Error('И-мэйл болон нууц үгээ зөв оруулна уу.');showStatus($('authStatus'),'Бүртгэл үүсгэж байна…');const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin}});if(error)throw error;if(data.session){session=data.session;await authReady()}else showStatus($('authStatus'),'Бүртгэл үүслээ. И-мэйлээ баталгаажуулаад Нэвтрэх дарна уу.','ok')}catch(e){showStatus($('authStatus'),'Бүртгүүлэх алдаа: '+e.message,'err')}};
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
async function ownerCall(body){const {data,error}=await sb.functions.invoke('schoollink-owner-dashboard',{body});if(error)throw new Error(error.message||'Owner API алдаа');if(data?.error)throw new Error(data.error);return data;}
async function loadOwner(){try{ownerData=await ownerCall({action:'overview'});const m=ownerData.metrics||{};$('ownerMetrics').innerHTML=[['Сургууль',m.schools],['Хэрэглэгч',m.users],['Сурагч',m.students],['Багш',m.teachers],['Эцэг эх',m.parents],['Анги',m.classes]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]||0}</b></div>`).join('');const rows=ownerData.schools||[];$('ownerSchools').className=rows.length?'':'empty';$('ownerSchools').innerHTML=rows.length?rows.map(s=>`<div class="ownerSchool"><div><h4>${esc(s.name)}</h4><div class="muted">${esc(s.code)} · ${s.counts?.classes||0} анги · ${s.counts?.students||0} сурагч · ${s.counts?.teachers||0} багш</div></div><div class="schoolActions"><span class="pill">${esc(s.subscription?.plan||'trial')} / ${esc(s.subscription?.status||'setup')}</span><button class="ghost" onclick="openSchool('${s.id}')">⚙ Тохируулах</button></div></div>`).join(''):'Одоогоор сургууль алга байна.';}catch(e){$('ownerSchools').className='status show err';$('ownerSchools').textContent='Owner мэдээлэл: '+e.message}}
function openNewSchool(){currentSchool=null;currentDetail=null;$('schoolModal').classList.remove('hidden');$('newSchoolPane').classList.remove('hidden');$('schoolSetupPane').classList.add('hidden');$('schoolModalTitle').textContent='Шинэ сургууль';$('newSchoolName').value='';clearStatus($('newSchoolStatus'));}
function closeSchoolModal(){$('schoolModal').classList.add('hidden')}
async function createSchool(){try{const name=$('newSchoolName').value.trim();if(name.length<2)throw new Error('Сургуулийн нэрээ оруулна уу.');$('createSchoolBtn').disabled=true;showStatus($('newSchoolStatus'),'Сургууль үүсгэж байна…');const data=await ownerCall({action:'create_school',school_name:name,trial_days:Number($('trialDays').value)});showStatus($('newSchoolStatus'),'Сургууль амжилттай үүслээ ✅','ok');await loadOwner();await openSchool(data.school.id);}catch(e){showStatus($('newSchoolStatus'),e.message,'err')}finally{$('createSchoolBtn').disabled=false}}
async function openSchool(id){$('schoolModal').classList.remove('hidden');$('newSchoolPane').classList.add('hidden');$('schoolSetupPane').classList.remove('hidden');currentSchool=id;await refreshSchoolDetail();}
async function refreshSchoolDetail(){try{currentDetail=await ownerCall({action:'school_detail',school_id:currentSchool});const s=currentDetail.school;$('schoolModalTitle').textContent=s.name;$('schoolSummary').innerHTML=`<b>${esc(s.name)}</b><p>Код: ${esc(s.code)} · ${currentDetail.counts.classes} анги · ${currentDetail.counts.students} сурагч · ${currentDetail.counts.teachers} багш</p>`;renderClasses();renderStudents();fillSelects();}catch(e){$('schoolSummary').innerHTML='<span style="color:#a12b2b">'+esc(e.message)+'</span>'}}
function renderClasses(){const rows=currentDetail?.classes||[];$('classList').className=rows.length?'list':'empty';$('classList').innerHTML=rows.length?rows.map(c=>`<div class="row"><div><b>${esc(c.name)}</b><small> · ${esc(c.academic_year)}${c.grade?' · '+c.grade+'-р анги':''}</small></div><span class="pill">${esc(c.section||'')}</span></div>`).join(''):'Анги алга.';}
function renderStudents(){const rows=currentDetail?.students||[];$('studentList').className=rows.length?'list':'empty';$('studentList').innerHTML=rows.length?rows.map(s=>`<div class="row"><div><b>${esc(s.full_name)}</b><small> · ${esc(s.student_code||'кодгүй')}</small></div></div>`).join(''):'Сурагч алга.';}
function fillSelects(){const classes=currentDetail?.classes||[],students=currentDetail?.students||[];const copt=classes.length?classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join(''):'<option value="">Эхлээд анги нэмнэ үү</option>';$('studentClass').innerHTML=copt;$('inviteClass').innerHTML='<option value="">Анги сонгохгүй</option>'+copt;$('inviteStudent').innerHTML=students.length?students.map(s=>`<option value="${s.id}">${esc(s.full_name)}</option>`).join(''):'<option value="">Эхлээд сурагч нэмнэ үү</option>';}
async function createClass(){try{const name=$('className').value.trim();if(!name)throw new Error('Ангийн нэр шаардлагатай.');showStatus($('classStatus'),'Анги нэмэж байна…');await ownerCall({action:'create_class',school_id:currentSchool,name,grade:$('classGrade').value,section:$('classSection').value,academic_year:$('academicYear').value.trim()||'2026-2027'});showStatus($('classStatus'),'Анги амжилттай нэмэгдлээ ✅','ok');$('className').value='';$('classGrade').value='';$('classSection').value='';await refreshSchoolDetail();await loadOwner();}catch(e){showStatus($('classStatus'),e.message,'err')}}
async function createStudent(){try{const class_id=$('studentClass').value,full_name=$('studentName').value.trim();if(!class_id||full_name.length<2)throw new Error('Анги болон сурагчийн нэр шаардлагатай.');showStatus($('studentStatus'),'Сурагч нэмэж байна…');await ownerCall({action:'create_student',school_id:currentSchool,class_id,full_name,student_code:$('studentCode').value.trim(),birth_date:$('studentBirth').value});showStatus($('studentStatus'),'Сурагч амжилттай нэмэгдлээ ✅','ok');$('studentName').value='';$('studentCode').value='';$('studentBirth').value='';await refreshSchoolDetail();await loadOwner();}catch(e){showStatus($('studentStatus'),e.message,'err')}}
function updateInviteFields(){const role=$('inviteRole').value;$('inviteClassWrap').classList.toggle('hidden',role==='admin');$('inviteStudentWrap').classList.toggle('hidden',role!=='parent');}
async function createInvite(){try{const role=$('inviteRole').value,body={action:'create_invite',school_id:currentSchool,role,expires_hours:168,max_uses:1};if(role==='teacher'&&$('inviteClass').value)body.class_id=$('inviteClass').value;if(role==='parent'){if(!$('inviteStudent').value)throw new Error('Эцэг эхийн урилгад сурагч сонгоно уу.');body.student_id=$('inviteStudent').value;}showStatus($('inviteStatus'),'Урилга үүсгэж байна…');const data=await ownerCall(body);showStatus($('inviteStatus'),`${role==='admin'?'Админ':role==='teacher'?'Багш':'Эцэг эх'} урилгын код бэлэн ✅`,'ok');$('inviteCodeBox').textContent=data.code;$('inviteCodeBox').classList.remove('hidden');}catch(e){showStatus($('inviteStatus'),e.message,'err')}}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.setupPane').forEach(x=>x.classList.remove('active'));$('setup-'+b.dataset.setup).classList.add('active')});
const navs={owner:['Dashboard','Сургуулиуд','Analytics','Багц & төлбөр'],teacher:['Нүүр','Мэдээлэл','Даалгавар','Ирц','Чат','Манай анги','Зөвшөөрөл','Ажлын сан','Ажиглалт','Сарын тайлан'],parent:['Нүүр','Миний хүүхэд','Мэдээлэл','Даалгавар','Багштай чат','Ахиц / Portfolio'],admin:['Нүүр','Ангиуд','Багш нар','Сурагчид','Мэдээлэл','Тайлан']};
function setRole(role){currentRole=role;document.querySelectorAll('.rolebar button').forEach(b=>b.classList.toggle('active',b.dataset.role===role));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===role));$('title').textContent={owner:'Owner Dashboard',teacher:'Багшийн Dashboard',parent:'Эцэг эхийн Dashboard',admin:'Удирдлагын Dashboard'}[role];$('profileName').textContent={owner:'Platform Owner',teacher:'Багш',parent:'Эцэг эх',admin:'Сургуулийн удирдлага'}[role];$('nav').innerHTML=navs[role].map((x,i)=>`<button class="${i===0?'active':''}">${x}</button>`).join('');}
document.querySelectorAll('.rolebar button').forEach(b=>b.onclick=()=>setRole(b.dataset.role));
setRole('owner');updateInviteFields();authReady();