const SUPABASE_URL='https://cfyxcopixetvlvhjftxv.supabase.co';
const SUPABASE_KEY='sb_publishable_1qWG5IZvHmfEOADJwCGhFg_79aZgQDq';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
let session=null,ownerData=null,membership=null,currentSchool=null,currentDetail=null,currentRole='owner',accessMode='none',teacherData=null;
function showStatus(el,msg,type=''){if(!el)return;el.textContent=msg;el.className='status show'+(type?' '+type:'')}
function clearStatus(el){if(!el)return;el.textContent='';el.className='status'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function savePendingInvite(){const code=($('authInviteCode')?.value||'').trim().toUpperCase(),fullName=($('authFullName')?.value||'').trim();if(code)localStorage.setItem('schoollink_pending_invite',JSON.stringify({code,fullName}));else localStorage.removeItem('schoollink_pending_invite')}
function readPendingInvite(){try{return JSON.parse(localStorage.getItem('schoollink_pending_invite')||'null')}catch{return null}}
function clearPendingInvite(){localStorage.removeItem('schoollink_pending_invite')}
async function onboardingCall(body){const {data,error}=await sb.functions.invoke('schoollink-onboarding',{body});if(error)throw new Error(error.message||'Onboarding API алдаа');if(data?.error)throw new Error(data.error);return data}
async function ownerCall(body){const {data,error}=await sb.functions.invoke('schoollink-owner-dashboard',{body});if(error)throw new Error(error.message||'Owner API алдаа');if(data?.error)throw new Error(data.error);return data}
async function redeemInviteCode(code,fullName){const result=await onboardingCall({action:'redeem_invite',code,full_name:fullName||''});if(result.role==='teacher'&&result.class_id){await sb.from('classes').update({homeroom_teacher_id:session.user.id}).eq('id',result.class_id).eq('school_id',result.school_id)}return result}
async function redeemPendingInvite(){const pending=readPendingInvite();if(!pending?.code)return null;const result=await redeemInviteCode(pending.code,pending.fullName);clearPendingInvite();return result}
async function getMembership(){const {data,error}=await sb.from('school_members').select('school_id,role,status,schools(name,code)').eq('user_id',session.user.id).eq('status','active').limit(1);if(error)throw error;return data?.[0]||null}
async function resolveAccess(){
  $('authWrap').classList.add('hidden');$('joinWrap').classList.add('hidden');$('app').classList.add('hidden');
  try{await redeemPendingInvite()}catch(e){$('joinWrap').classList.remove('hidden');showStatus($('joinStatus'),'Урилгын код: '+e.message,'err');return}
  try{ownerData=await ownerCall({action:'overview'});accessMode='owner';membership=null;$('app').classList.remove('hidden');document.querySelector('.rolebar').classList.remove('hidden');$('memberSchool').classList.add('hidden');$('ownerEmail').textContent=session.user.email||'';$('profileMeta').textContent=session.user.email||'';setRole('owner');renderOwnerData();return}catch(_){ }
  try{membership=await getMembership()}catch(_){membership=null}
  if(membership){accessMode='member';$('app').classList.remove('hidden');document.querySelector('.rolebar').classList.add('hidden');$('profileMeta').textContent=session.user.email||'';$('memberSchool').textContent=membership.schools?.name||'Сургууль';$('memberSchool').classList.remove('hidden');const role=membership.role==='admin'?'admin':membership.role;setRole(role);if(role==='teacher')await loadTeacherDashboard();return}
  accessMode='none';$('joinWrap').classList.remove('hidden');const p=readPendingInvite();if(p){$('joinInviteCode').value=p.code||'';$('joinFullName').value=p.fullName||''}
}
async function authReady(){const {data}=await sb.auth.getSession();session=data.session;if(session)await resolveAccess();else{$('authWrap').classList.remove('hidden');$('joinWrap').classList.add('hidden');$('app').classList.add('hidden')}}
$('login').onclick=async()=>{try{clearStatus($('authStatus'));const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<6)throw new Error('И-мэйл болон нууц үгээ зөв оруулна уу.');savePendingInvite();showStatus($('authStatus'),'Нэвтэрч байна…');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;session=data.session;await resolveAccess()}catch(e){showStatus($('authStatus'),'Нэвтрэх алдаа: '+e.message,'err')}};
$('signup').onclick=async()=>{try{clearStatus($('authStatus'));const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<6)throw new Error('И-мэйл болон нууц үгээ зөв оруулна уу.');savePendingInvite();showStatus($('authStatus'),'Бүртгэл үүсгэж байна…');const {data,error}=await sb.auth.signUp({email,password});if(error)throw error;if(data.session){session=data.session;await resolveAccess()}else showStatus($('authStatus'),'Бүртгэл үүслээ. Одоо Нэвтрэх дарна уу.','ok')}catch(e){showStatus($('authStatus'),'Бүртгүүлэх алдаа: '+e.message,'err')}};
$('logout').onclick=async()=>{clearPendingInvite();await sb.auth.signOut();location.reload()};
$('joinLogout').onclick=async()=>{clearPendingInvite();await sb.auth.signOut();location.reload()};
$('joinBtn').onclick=async()=>{try{clearStatus($('joinStatus'));const code=$('joinInviteCode').value.trim().toUpperCase(),fullName=$('joinFullName').value.trim();if(code.length<6)throw new Error('Урилгын кодоо зөв оруулна уу.');showStatus($('joinStatus'),'Сургуультай холбож байна…');await redeemInviteCode(code,fullName);showStatus($('joinStatus'),'Амжилттай нэгдлээ ✅','ok');setTimeout(resolveAccess,250)}catch(e){showStatus($('joinStatus'),'Нэгдэх алдаа: '+e.message,'err')}};

function renderOwnerData(){const m=ownerData?.metrics||{};$('ownerMetrics').innerHTML=[['Сургууль',m.schools],['Хэрэглэгч',m.users],['Сурагч',m.students],['Багш',m.teachers],['Эцэг эх',m.parents],['Анги',m.classes]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]||0}</b></div>`).join('');const rows=ownerData?.schools||[];$('ownerSchools').className=rows.length?'':'empty';$('ownerSchools').innerHTML=rows.length?rows.map(s=>`<div class="ownerSchool"><div><h4>${esc(s.name)}</h4><div class="muted">${esc(s.code)} · ${s.counts?.classes||0} анги · ${s.counts?.students||0} сурагч · ${s.counts?.teachers||0} багш</div></div><div class="schoolActions"><span class="pill">${esc(s.subscription?.plan||'trial')} / ${esc(s.subscription?.status||'setup')}</span><button class="ghost" onclick="openSchool('${s.id}')">⚙ Тохируулах</button></div></div>`).join(''):'Одоогоор сургууль алга байна.'}
async function loadOwner(){try{ownerData=await ownerCall({action:'overview'});renderOwnerData()}catch(e){$('ownerSchools').className='status show err';$('ownerSchools').textContent='Owner мэдээлэл: '+e.message}}
function openNewSchool(){currentSchool=null;currentDetail=null;$('schoolModal').classList.remove('hidden');$('newSchoolPane').classList.remove('hidden');$('schoolSetupPane').classList.add('hidden');$('schoolModalTitle').textContent='Шинэ сургууль';$('newSchoolName').value='';clearStatus($('newSchoolStatus'))}
function closeSchoolModal(){$('schoolModal').classList.add('hidden')}
async function createSchool(){try{const name=$('newSchoolName').value.trim();if(name.length<2)throw new Error('Сургуулийн нэрээ оруулна уу.');$('createSchoolBtn').disabled=true;showStatus($('newSchoolStatus'),'Сургууль үүсгэж байна…');const data=await ownerCall({action:'create_school',school_name:name,trial_days:Number($('trialDays').value)});showStatus($('newSchoolStatus'),'Сургууль амжилттай үүслээ ✅','ok');await loadOwner();await openSchool(data.school.id)}catch(e){showStatus($('newSchoolStatus'),e.message,'err')}finally{$('createSchoolBtn').disabled=false}}
async function openSchool(id){$('schoolModal').classList.remove('hidden');$('newSchoolPane').classList.add('hidden');$('schoolSetupPane').classList.remove('hidden');currentSchool=id;await refreshSchoolDetail()}
async function refreshSchoolDetail(){try{currentDetail=await ownerCall({action:'school_detail',school_id:currentSchool});const s=currentDetail.school;$('schoolModalTitle').textContent=s.name;$('schoolSummary').innerHTML=`<b>${esc(s.name)}</b><p>Код: ${esc(s.code)} · ${currentDetail.counts.classes} анги · ${currentDetail.counts.students} сурагч · ${currentDetail.counts.teachers} багш</p>`;renderClasses();renderStudents();fillSelects()}catch(e){$('schoolSummary').innerHTML='<span style="color:#a12b2b">'+esc(e.message)+'</span>'}}
function renderClasses(){const rows=currentDetail?.classes||[];$('classList').className=rows.length?'list':'empty';$('classList').innerHTML=rows.length?rows.map(c=>`<div class="row"><div><b>${esc(c.name)}</b><small> · ${esc(c.academic_year)}${c.grade?' · '+c.grade+'-р анги':''}</small></div><span class="pill">${esc(c.section||'')}</span></div>`).join(''):'Анги алга.'}
function renderStudents(){const rows=currentDetail?.students||[];$('studentList').className=rows.length?'list':'empty';$('studentList').innerHTML=rows.length?rows.map(s=>`<div class="row"><div><b>${esc(s.full_name)}</b><small> · ${esc(s.student_code||'кодгүй')}</small></div></div>`).join(''):'Сурагч алга.'}
function fillSelects(){const classes=currentDetail?.classes||[],students=currentDetail?.students||[];const opts=classes.length?classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join(''):'<option value="">Эхлээд анги нэмнэ үү</option>';$('studentClass').innerHTML=opts;$('inviteClass').innerHTML='<option value="">Анги сонгохгүй</option>'+opts;$('inviteStudent').innerHTML=students.length?students.map(s=>`<option value="${s.id}">${esc(s.full_name)}</option>`).join(''):'<option value="">Эхлээд сурагч нэмнэ үү</option>'}
async function createClass(){try{const name=$('className').value.trim();if(!name)throw new Error('Ангийн нэр шаардлагатай.');showStatus($('classStatus'),'Анги нэмж байна…');await ownerCall({action:'create_class',school_id:currentSchool,name,grade:$('classGrade').value,section:$('classSection').value,academic_year:$('academicYear').value.trim()||'2026-2027'});showStatus($('classStatus'),'Анги амжилттай нэмэгдлээ ✅','ok');$('className').value='';$('classGrade').value='';$('classSection').value='';await refreshSchoolDetail();await loadOwner()}catch(e){showStatus($('classStatus'),e.message,'err')}}
async function createStudent(){try{const class_id=$('studentClass').value,full_name=$('studentName').value.trim();if(!class_id||full_name.length<2)throw new Error('Анги болон сурагчийн нэр шаардлагатай.');showStatus($('studentStatus'),'Сурагч нэмж байна…');await ownerCall({action:'create_student',school_id:currentSchool,class_id,full_name,student_code:$('studentCode').value.trim(),birth_date:$('studentBirth').value});showStatus($('studentStatus'),'Сурагч амжилттай нэмэгдлээ ✅','ok');$('studentName').value='';$('studentCode').value='';$('studentBirth').value='';await refreshSchoolDetail();await loadOwner()}catch(e){showStatus($('studentStatus'),e.message,'err')}}
function updateInviteFields(){const role=$('inviteRole').value;$('inviteClassWrap').classList.toggle('hidden',role==='admin');$('inviteStudentWrap').classList.toggle('hidden',role!=='parent')}
async function createInvite(){try{const role=$('inviteRole').value,body={action:'create_invite',school_id:currentSchool,role,expires_hours:168,max_uses:1};if(role==='teacher'&&$('inviteClass').value)body.class_id=$('inviteClass').value;if(role==='parent'){if(!$('inviteStudent').value)throw new Error('Эцэг эхийн урилгад сурагч сонгоно уу.');body.student_id=$('inviteStudent').value}showStatus($('inviteStatus'),'Урилга үүсгэж байна…');const data=await ownerCall(body);showStatus($('inviteStatus'),`${role==='admin'?'Админ':role==='teacher'?'Багш':'Эцэг эх'} урилгын код бэлэн ✅`,'ok');$('inviteCodeBox').textContent=data.code;$('inviteCodeBox').classList.remove('hidden')}catch(e){showStatus($('inviteStatus'),e.message,'err')}}

document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.setupPane').forEach(x=>x.classList.remove('active'));$('setup-'+b.dataset.setup).classList.add('active')});

async function loadTeacherDashboard(){
  if(!session||!membership||membership.role!=='teacher')return;
  try{
    const schoolId=membership.school_id;
    const {data:classes,error:classErr}=await sb.from('classes').select('id,name,grade,section,academic_year,homeroom_teacher_id').eq('school_id',schoolId).eq('homeroom_teacher_id',session.user.id).order('created_at',{ascending:true});if(classErr)throw classErr;
    const cls=classes?.[0]||null;
    if(!cls){teacherData={schoolId,cls:null,students:[],attendance:[],assignments:[]};$('teacherHeroTitle').textContent='Танд анги хараахан холбогдоогүй байна.';$('teacherHeroMeta').textContent='Owner багшийн урилгыг ангитай холбож үүсгэнэ.';$('teacherStudents').className='empty';$('teacherStudents').textContent='Анги холбогдоогүй.';$('teacherAssignments').className='empty';$('teacherAssignments').textContent='Даалгавар алга.';$('teacherAttendance').textContent='—';$('teacherStudentCount').textContent='0';$('teacherAttentionCount').textContent='0';$('teacherAssignmentCount').textContent='0';return}
    const date=new Date().toISOString().slice(0,10);
    const [{data:students,error:studentErr},{data:attendance,error:attErr},{data:assignments,error:assErr}]=await Promise.all([
      sb.from('students').select('id,full_name,student_code').eq('school_id',schoolId).eq('class_id',cls.id).eq('active',true).order('full_name'),
      sb.from('attendance').select('id,student_id,status,note,attendance_date').eq('school_id',schoolId).eq('class_id',cls.id).eq('attendance_date',date),
      sb.from('assignments').select('id,subject,title,description,due_at,created_at').eq('school_id',schoolId).eq('class_id',cls.id).eq('teacher_id',session.user.id).order('created_at',{ascending:false}).limit(8)
    ]);if(studentErr||attErr||assErr)throw studentErr||attErr||assErr;
    teacherData={schoolId,cls,students:students||[],attendance:attendance||[],assignments:assignments||[]};
    const attMap=new Map((attendance||[]).map(a=>[a.student_id,a])),present=(attendance||[]).filter(a=>a.status==='present').length,attention=(attendance||[]).filter(a=>['absent','late'].includes(a.status)).length;
    $('teacherHeroTitle').textContent=`${cls.name} анги · Өнөөдрийн ажил`;$('teacherHeroMeta').textContent=`${cls.academic_year||''}${cls.grade?' · '+cls.grade+'-р анги':''}`;$('teacherStudentCount').textContent=students?.length||0;$('teacherAttendance').textContent=students?.length?`${present}/${students.length}`:'—';$('teacherAttentionCount').textContent=attention;$('teacherAssignmentCount').textContent=assignments?.length||0;
    $('teacherStudents').className=students?.length?'list':'empty';$('teacherStudents').innerHTML=students?.length?students.map(st=>{const a=attMap.get(st.id),lab=a?({present:'Ирсэн',absent:'Тасалсан',late:'Хоцорсон',excused:'Чөлөөтэй'}[a.status]||a.status):'Бүртгээгүй';return `<div class="row"><div><b>${esc(st.full_name)}</b><small> · ${esc(st.student_code||'кодгүй')}</small></div><span class="pill">${lab}</span></div>`}).join(''):'Сурагч алга.';
    $('teacherAssignments').className=assignments?.length?'list':'empty';$('teacherAssignments').innerHTML=assignments?.length?assignments.map(a=>`<div class="row"><div><b>${esc(a.subject)} · ${esc(a.title)}</b><small>${a.due_at?' · '+new Date(a.due_at).toLocaleString('mn-MN'):''}</small></div></div>`).join(''):'Даалгавар алга.';
  }catch(e){$('teacherStudents').className='status show err';$('teacherStudents').textContent='Багшийн мэдээлэл: '+e.message}
}
function closeTeacherModal(id){$(id).classList.add('hidden')}
function openAttendanceModal(){if(!teacherData?.cls)return alert('Эхлээд багшид анги холбоно уу.');const map=new Map((teacherData.attendance||[]).map(a=>[a.student_id,a.status]));$('attendanceList').innerHTML=(teacherData.students||[]).map(st=>`<div class="row"><div><b>${esc(st.full_name)}</b></div><select data-att-student="${st.id}" style="max-width:170px"><option value="present" ${map.get(st.id)==='present'?'selected':''}>Ирсэн</option><option value="late" ${map.get(st.id)==='late'?'selected':''}>Хоцорсон</option><option value="absent" ${map.get(st.id)==='absent'?'selected':''}>Тасалсан</option><option value="excused" ${map.get(st.id)==='excused'?'selected':''}>Чөлөөтэй</option></select></div>`).join('');clearStatus($('attendanceStatus'));$('attendanceModal').classList.remove('hidden')}
async function saveAttendance(){try{if(!teacherData?.cls)throw new Error('Анги холбогдоогүй.');showStatus($('attendanceStatus'),'Хадгалж байна…');const date=new Date().toISOString().slice(0,10),existing=new Map((teacherData.attendance||[]).map(a=>[a.student_id,a.id]));for(const el of document.querySelectorAll('[data-att-student]')){const row={school_id:teacherData.schoolId,class_id:teacherData.cls.id,student_id:el.dataset.attStudent,attendance_date:date,status:el.value,marked_by:session.user.id,marked_at:new Date().toISOString()},id=existing.get(row.student_id);const {error}=id?await sb.from('attendance').update(row).eq('id',id):await sb.from('attendance').insert(row);if(error)throw error}showStatus($('attendanceStatus'),'Ирц хадгалагдлаа ✅','ok');await loadTeacherDashboard()}catch(e){showStatus($('attendanceStatus'),e.message,'err')}}
function openAssignmentModal(){if(!teacherData?.cls)return alert('Эхлээд багшид анги холбоно уу.');clearStatus($('assignmentStatus'));$('assignmentModal').classList.remove('hidden')}
async function saveAssignment(){try{const subject=$('assignmentSubject').value.trim(),title=$('assignmentTitle').value.trim();if(!subject||!title)throw new Error('Хичээл болон гарчгаа оруулна уу.');showStatus($('assignmentStatus'),'Хадгалж байна…');const {error}=await sb.from('assignments').insert({school_id:teacherData.schoolId,class_id:teacherData.cls.id,teacher_id:session.user.id,subject,title,description:$('assignmentDesc').value.trim()||null,due_at:$('assignmentDue').value?new Date($('assignmentDue').value).toISOString():null});if(error)throw error;showStatus($('assignmentStatus'),'Даалгавар нэмэгдлээ ✅','ok');$('assignmentSubject').value='';$('assignmentTitle').value='';$('assignmentDesc').value='';$('assignmentDue').value='';await loadTeacherDashboard()}catch(e){showStatus($('assignmentStatus'),e.message,'err')}}

const navs={owner:['Dashboard','Сургуулиуд','Analytics','Багц & төлбөр'],teacher:['Нүүр','Мэдээлэл','Даалгавар','Ирц','Чат','Манай анги','Зөвшөөрөл','Ажлын сан','Ажиглалт','Сарын тайлан'],parent:['Нүүр','Миний хүүхэд','Мэдээлэл','Даалгавар','Багштай чат','Ахиц / Portfolio'],admin:['Нүүр','Ангиуд','Багш нар','Сурагчид','Мэдээлэл','Тайлан']};
function setRole(role){if(accessMode==='member'&&membership)role=membership.role==='admin'?'admin':membership.role;currentRole=role;document.querySelectorAll('.rolebar button').forEach(b=>b.classList.toggle('active',b.dataset.role===role));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===role));$('title').textContent={owner:'Owner Dashboard',teacher:'Багшийн Dashboard',parent:'Эцэг эхийн Dashboard',admin:'Удирдлагын Dashboard'}[role];$('profileName').textContent={owner:'Platform Owner',teacher:'Багш',parent:'Эцэг эх',admin:'Сургуулийн удирдлага'}[role];$('nav').innerHTML=navs[role].map((x,i)=>`<button class="${i===0?'active':''}">${x}</button>`).join('');if(role==='teacher'&&membership)loadTeacherDashboard()}
document.querySelectorAll('.rolebar button').forEach(b=>b.onclick=()=>{if(accessMode==='owner')setRole(b.dataset.role)});
updateInviteFields();authReady();