let parentProChatId=null;
function ppKindLabel(k){return ({notice:'Мэдээлэл',reminder:'Сануулга',urgent:'Яаралтай',event:'Үйл явдал',homework:'Даалгавар'})[k]||'Мэдээлэл'}
function ppResponseLabel(r){return r==='approved'?'✅ Зөвшөөрсөн':r==='declined'?'❌ Татгалзсан':'Хариулаагүй'}
async function ppChat(body){const {data,error}=await sb.functions.invoke('schoollink-chat',{body});if(error)throw new Error(error.message||'Chat API алдаа');if(data?.error)throw new Error(data.error);return data}
function ppEnsureCards(){const grid=document.querySelector('#parent .grid');if(!grid||document.getElementById('parentAnnouncements'))return;grid.insertAdjacentHTML('beforeend',`
<div class="card wide"><div class="sectionTitle"><h3>Сургуулийн мэдээлэл</h3><span id="parentUnreadBadge" class="pill">0 уншаагүй</span></div><div id="parentAnnouncements" class="empty">Мэдээлэл ачаалж байна…</div></div>
<div class="card narrow"><div class="sectionTitle"><h3>Зөвшөөрөл</h3></div><div id="parentPermissions" class="empty">Хүсэлт ачаалж байна…</div><div id="parentPermissionStatus" class="status"></div></div>
<div class="card full"><div class="sectionTitle"><h3>Багштай чат</h3><button class="ghost" onclick="ppReloadChat()">↻ Шинэчлэх</button></div><div id="parentChatThreads" class="empty">Чат ачаалж байна…</div><div id="parentChatBox" class="hidden"><div id="parentChatMessages" class="chatBox"></div><div class="schoolActions"><input id="parentChatInput" placeholder="Багшдаа мессеж бичих…" style="flex:1"><button class="btn primary" onclick="ppSendMessage()">Илгээх</button></div><div id="parentChatStatus" class="status"></div></div></div>`)}
async function ppLoadAnnouncements(){const child=parentData?.child;if(!child||!$('parentAnnouncements'))return;let q=sb.from('announcements').select('id,title,body,kind,due_at,published_at,created_at,scope,class_id').eq('school_id',membership.school_id).order('published_at',{ascending:false}).limit(20);if(child.class_id)q=q.or(`scope.eq.school,class_id.eq.${child.class_id}`);else q=q.eq('scope','school');const {data:rows,error}=await q;if(error)throw error;const ids=(rows||[]).map(x=>x.id);const {data:reads,error:re}=ids.length?await sb.from('announcement_reads').select('announcement_id,read_at').eq('user_id',session.user.id).in('announcement_id',ids):{data:[],error:null};if(re)throw re;const readSet=new Set((reads||[]).map(x=>x.announcement_id)),unread=(rows||[]).filter(x=>!readSet.has(x.id)).length;$('parentUnreadBadge').textContent=`${unread} уншаагүй`;$('parentAnnouncements').className=rows?.length?'list':'empty';$('parentAnnouncements').innerHTML=rows?.length?rows.map(a=>`<div class="notice"><div class="sectionTitle"><b>${readSet.has(a.id)?'✓':'●'} ${esc(a.title)}</b><span class="pill">${ppKindLabel(a.kind)}</span></div><p>${esc(a.body)}</p><small>${parentFmtDate(a.published_at||a.created_at)}${a.due_at?' · Хугацаа: '+parentFmtDate(a.due_at):''}</small>${!readSet.has(a.id)?`<div style="margin-top:8px"><button class="ghost" onclick="ppMarkRead('${a.id}')">Уншсан гэж тэмдэглэх</button></div>`:''}</div>`).join(''):'Мэдээлэл алга.'}
window.ppMarkRead=async id=>{try{await sb.from('announcement_reads').upsert({announcement_id:id,user_id:session.user.id,read_at:new Date().toISOString()},{onConflict:'announcement_id,user_id'});await ppLoadAnnouncements()}catch(e){alert(e.message)}};
async function ppLoadPermissions(){const child=parentData?.child;if(!child||!$('parentPermissions'))return;let q=sb.from('permissions').select('id,title,description,due_at,created_at,class_id').eq('school_id',membership.school_id).order('created_at',{ascending:false}).limit(20);if(child.class_id)q=q.eq('class_id',child.class_id);else q=q.is('class_id',null);const {data:rows,error}=await q;if(error)throw error;const ids=(rows||[]).map(x=>x.id);const {data:responses,error:re}=ids.length?await sb.from('permission_responses').select('permission_id,response,responded_at').eq('guardian_user_id',session.user.id).eq('student_id',child.id).in('permission_id',ids):{data:[],error:null};if(re)throw re;const map=new Map((responses||[]).map(x=>[x.permission_id,x]));$('parentPermissions').className=rows?.length?'list':'empty';$('parentPermissions').innerHTML=rows?.length?rows.map(p=>{const r=map.get(p.id),expired=!!p.due_at&&new Date(p.due_at).getTime()<Date.now();return `<div class="notice"><b>${esc(p.title)}</b>${p.description?`<p>${esc(p.description)}</p>`:''}<small>${p.due_at?'Хариу өгөх хугацаа: '+parentFmtDate(p.due_at):''}</small><div style="margin-top:8px"><span class="pill">${ppResponseLabel(r?.response)}</span>${expired&&!r?'<span class="pill" style="margin-left:6px">Хугацаа дууссан</span>':''}</div>${!r&&!expired?`<div class="schoolActions" style="margin-top:8px"><button class="ghost" onclick="ppRespondPermission('${p.id}','approved')">✅ Зөвшөөрөх</button><button class="ghost" onclick="ppRespondPermission('${p.id}','declined')">❌ Татгалзах</button></div>`:''}</div>`}).join(''):'Зөвшөөрлийн хүсэлт алга.'}
window.ppRespondPermission=async(permissionId,response)=>{try{showStatus($('parentPermissionStatus'),'Хариуг хадгалж байна…');const {data:p,error:pe}=await sb.from('permissions').select('due_at,class_id').eq('id',permissionId).maybeSingle();if(pe)throw pe;if(!p)throw new Error('Зөвшөөрлийн хүсэлт олдсонгүй.');if(parentData?.child?.class_id&&p.class_id!==parentData.child.class_id)throw new Error('Энэ хүсэлт таны хүүхдийн ангид хамаарахгүй байна.');if(p.due_at&&new Date(p.due_at).getTime()<Date.now())throw new Error('Хариу өгөх хугацаа дууссан байна.');const {error}=await sb.from('permission_responses').upsert({permission_id:permissionId,student_id:parentData.child.id,guardian_user_id:session.user.id,response,responded_at:new Date().toISOString()},{onConflict:'permission_id,student_id,guardian_user_id'});if(error)throw error;showStatus($('parentPermissionStatus'),'Хариу хадгалагдлаа ✅','ok');await ppLoadPermissions()}catch(e){showStatus($('parentPermissionStatus'),e.message,'err')}};
async function ppLoadChat(){if(!$('parentChatThreads')||!parentData?.child)return;const d=await ppChat({action:'list'}),threads=(d.threads||[]).filter(t=>t.student_id===parentData.child.id);$('parentChatThreads').className=threads.length?'list':'empty';$('parentChatThreads').innerHTML=threads.length?threads.map(t=>`<button class="mini actionMini tpFull" onclick="ppOpenChat('${t.id}')">💬 ${esc(t.student_name||parentData.child.full_name)}</button>`).join(''):'Одоогоор чат эхлээгүй байна. Багш чат эхлүүлсний дараа энд харагдана.';if(threads[0])await ppOpenChat(threads[0].id)}
window.ppOpenChat=async id=>{try{parentProChatId=id;const d=await ppChat({action:'messages',conversation_id:id});$('parentChatBox').classList.remove('hidden');$('parentChatMessages').innerHTML=d.messages?.length?d.messages.map(m=>`<div class="chatMsg ${m.sender_id===d.user_id?'mine':''}"><b>${m.sender_id===d.user_id?'Би':'Багш'}</b><div>${esc(m.body)}</div><small>${parentFmtDate(m.created_at)}</small></div>`).join(''):'<div class="empty">Мессеж алга.</div>';$('parentChatMessages').scrollTop=$('parentChatMessages').scrollHeight}catch(e){showStatus($('parentChatStatus'),e.message,'err')}};
window.ppSendMessage=async()=>{try{const body=$('parentChatInput').value.trim();if(!body||!parentProChatId)return;await ppChat({action:'send',conversation_id:parentProChatId,body,priority:'normal'});$('parentChatInput').value='';await ppOpenChat(parentProChatId)}catch(e){showStatus($('parentChatStatus'),e.message,'err')}};
window.ppReloadChat=()=>ppLoadChat();
async function ppEnhanceParent(){if(!session||!membership||membership.role!=='parent'||!parentData?.child)return;ppEnsureCards();try{await Promise.all([ppLoadAnnouncements(),ppLoadPermissions(),ppLoadChat()])}catch(e){console.warn('Parent pro',e);if($('parentAnnouncements'))$('parentAnnouncements').innerHTML=`<div class="status show err">${esc(e.message)}</div>`}}
const ppBaseLoadParent=loadParentDashboard;loadParentDashboard=async function(studentId=null){await ppBaseLoadParent(studentId);await ppEnhanceParent()};
setTimeout(()=>{if(typeof currentRole!=='undefined'&&currentRole==='parent'&&membership)ppEnhanceParent()},500);
