let teacherHomeTemplate=null,teacherProReady=false,teacherCurrentView='Нүүр',teacherCtx=null,teacherChatId=null;

function tpEsc(s){return esc(s)}
function tpFmt(v){if(!v)return '';try{return new Date(v).toLocaleString('mn-MN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}catch{return String(v)}}
function tpFileIcon(mime=''){return mime.startsWith('image/')?'🖼️':mime.includes('pdf')?'📕':mime.includes('word')?'📘':mime.includes('sheet')||mime.includes('excel')?'📗':mime.includes('presentation')?'📙':'📎'}
async function tpWorkflow(body){const {data,error}=await sb.functions.invoke('schoollink-school-workflow',{body});if(error)throw new Error(error.message||'School workflow алдаа');if(data?.error)throw new Error(data.error);return data}
async function tpChat(body){const {data,error}=await sb.functions.invoke('schoollink-chat',{body});if(error)throw new Error(error.message||'Chat API алдаа');if(data?.error&&!data?.needs_parent)throw new Error(data.error);return data}
async function tpContext(){const d=await tpWorkflow({action:'context'});teacherCtx=d;if(!d.access_open)throw new Error('SchoolLink ашиглах эрх идэвхжээгүй байна.');if(d.class){teacherData=teacherData||{};teacherData.schoolId=membership.school_id;teacherData.cls=d.class;teacherData.students=d.students||[]}return d}
async function tpOpenFile(path,bucket='assignment-files'){const {data,error}=await sb.storage.from(bucket).createSignedUrl(path,3600);if(error)throw error;window.open(data.signedUrl,'_blank','noopener')}
window.tpOpenFile=tpOpenFile;

function tpEnsureAssignmentFiles(){const modal=$('assignmentModal');if(!modal||$('assignmentFiles'))return;const status=$('assignmentStatus');const wrap=document.createElement('div');wrap.innerHTML=`<label>Файл / зураг хавсаргах</label><input id="assignmentFiles" type="file" multiple accept="image/png,image/jpeg,image/webp,application/pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt"><div class="muted" style="font-size:12px;margin-top:6px">Нэг файл 20MB хүртэл. Олон файл сонгож болно.</div>`;modal.querySelector('.modalCard').insertBefore(wrap,status)}

async function tpUploadAssignmentFiles(assignment,files){const uploaded=[];for(const file of files){if(file.size>20*1024*1024)throw new Error(`${file.name} 20MB-аас их байна.`);const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'_'),path=`${teacherData.schoolId}/${assignment.id}/${session.user.id}/${Date.now()}_${crypto.randomUUID()}_${safe}`;const {error:upErr}=await sb.storage.from('assignment-files').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(upErr)throw upErr;const {error:metaErr}=await sb.from('assignment_attachments').insert({school_id:teacherData.schoolId,class_id:teacherData.cls.id,assignment_id:assignment.id,uploader_user_id:session.user.id,file_path:path,file_name:file.name,mime_type:file.type||null,file_size:file.size});if(metaErr){await sb.storage.from('assignment-files').remove([path]);throw metaErr}uploaded.push(path)}return uploaded}

const tpOriginalSaveAssignment=window.saveAssignment;
window.saveAssignment=async function(){try{const subject=$('assignmentSubject').value.trim(),title=$('assignmentTitle').value.trim();if(!subject||!title)throw new Error('Хичээл болон гарчгаа оруулна уу.');if(!teacherData?.cls)await tpContext();showStatus($('assignmentStatus'),'Даалгавар хадгалж байна…');const {data:assignment,error}=await sb.from('assignments').insert({school_id:teacherData.schoolId,class_id:teacherData.cls.id,teacher_id:session.user.id,subject,title,description:$('assignmentDesc').value.trim()||null,due_at:$('assignmentDue').value?new Date($('assignmentDue').value).toISOString():null}).select('*').single();if(error)throw error;const files=[...($('assignmentFiles')?.files||[])];if(files.length){showStatus($('assignmentStatus'),`Даалгавар хадгалагдлаа. ${files.length} файл байршуулж байна…`);await tpUploadAssignmentFiles(assignment,files)}showStatus($('assignmentStatus'),'Даалгавар болон хавсралт амжилттай нэмэгдлээ ✅','ok');$('assignmentSubject').value='';$('assignmentTitle').value='';$('assignmentDesc').value='';$('assignmentDue').value='';if($('assignmentFiles'))$('assignmentFiles').value='';await loadTeacherDashboard();if(teacherCurrentView==='Даалгавар')await tpRenderAssignments()}catch(e){showStatus($('assignmentStatus'),e.message,'err')}};

const tpOriginalLoadTeacher=window.loadTeacherDashboard;
window.loadTeacherDashboard=async function(){await tpOriginalLoadTeacher();try{if(!teacherData?.assignments?.length)return;const ids=teacherData.assignments.map(a=>a.id);const {data:atts,error}=await sb.from('assignment_attachments').select('*').in('assignment_id',ids).order('created_at');if(error)throw error;const by=new Map();(atts||[]).forEach(a=>{if(!by.has(a.assignment_id))by.set(a.assignment_id,[]);by.get(a.assignment_id).push(a)});if($('teacherAssignments'))$('teacherAssignments').innerHTML=teacherData.assignments.map(a=>{const fs=by.get(a.id)||[];return `<div class="notice"><b>${tpEsc(a.subject)} · ${tpEsc(a.title)}</b><p>${a.due_at?'Дуусах: '+tpFmt(a.due_at):'Хугацаагүй'}${a.description?' · '+tpEsc(a.description):''}</p>${fs.length?`<div class="schoolActions">${fs.map(f=>`<button class="ghost" onclick="tpOpenFile('${f.file_path.replaceAll("'","\\'")}')">${tpFileIcon(f.mime_type)} ${tpEsc(f.file_name)}</button>`).join('')}</div>`:''}</div>`}).join('')}catch(e){console.warn(e)}};

function tpTeacherSection(){return document.getElementById('teacher')}
function tpLayout(title,subtitle,body){tpTeacherSection().innerHTML=`<div class="grid"><div class="card hero full"><span class="pill">БАГШ</span><h3>${tpEsc(title)}</h3><p>${tpEsc(subtitle||'')}</p></div>${body}</div>`}
function tpBindNav(){if(currentRole!=='teacher')return;[...$('nav').querySelectorAll('button')].forEach(b=>{b.onclick=async()=>{[...$('nav').querySelectorAll('button')].forEach(x=>x.classList.toggle('active',x===b));teacherCurrentView=b.dataset.shLabel||b.textContent.trim();await tpRenderView(teacherCurrentView)}})}

async function tpRenderHome(){tpTeacherSection().innerHTML=teacherHomeTemplate;tpEnsureAssignmentFiles();await loadTeacherDashboard()}
async function tpRenderInfo(){const c=await tpContext();const {data,error}=await sb.from('announcements').select('*').eq('school_id',membership.school_id).eq('class_id',c.class.id).order('created_at',{ascending:false}).limit(30);if(error)throw error;tpLayout('Мэдээлэл','Ангидаа мэдээлэл, сануулга, зарлал нийтэлнэ.',`<div class="card narrow"><h3>Шинэ мэдээлэл</h3><label>Төрөл</label><select id="tpAnnKind"><option value="notice">Мэдээлэл</option><option value="reminder">Сануулга</option><option value="urgent">Яаралтай</option><option value="event">Үйл явдал</option></select><label>Гарчиг</label><input id="tpAnnTitle"><label>Текст</label><textarea id="tpAnnBody" class="tpTextarea"></textarea><button class="btn primary tpFull" onclick="tpSaveAnnouncement()">Нийтлэх</button><div id="tpAnnStatus" class="status"></div></div><div class="card wide"><div class="sectionTitle"><h3>Сүүлийн мэдээллүүд</h3></div><div>${data?.length?data.map(a=>`<div class="notice"><b>${tpEsc(a.title)}</b><p>${tpEsc(a.body)} · ${tpFmt(a.created_at)}</p></div>`).join(''):'<div class="empty">Мэдээлэл алга.</div>'}</div></div>`)}
window.tpSaveAnnouncement=async()=>{try{const c=await tpContext(),title=$('tpAnnTitle').value.trim(),body=$('tpAnnBody').value.trim();if(!title||!body)throw new Error('Гарчиг болон текстээ оруулна уу.');showStatus($('tpAnnStatus'),'Нийтэлж байна…');const {error}=await sb.from('announcements').insert({school_id:membership.school_id,class_id:c.class.id,author_id:session.user.id,scope:'class',kind:$('tpAnnKind').value,title,body});if(error)throw error;showStatus($('tpAnnStatus'),'Нийтлэгдлээ ✅','ok');await tpRenderInfo()}catch(e){showStatus($('tpAnnStatus'),e.message,'err')}};

async function tpRenderAssignments(){const c=await tpContext();const {data:rows,error}=await sb.from('assignments').select('*').eq('school_id',membership.school_id).eq('class_id',c.class.id).eq('teacher_id',session.user.id).order('created_at',{ascending:false});if(error)throw error;const ids=(rows||[]).map(x=>x.id);const {data:atts}=ids.length?await sb.from('assignment_attachments').select('*').in('assignment_id',ids):{data:[]};const by=new Map();(atts||[]).forEach(a=>{if(!by.has(a.assignment_id))by.set(a.assignment_id,[]);by.get(a.assignment_id).push(a)});tpLayout('Даалгавар','Файл, зурагтай даалгавар үүсгэж эцэг эхэд хүргэнэ.',`<div class="card full"><div class="sectionTitle"><h3>Даалгаврууд</h3><button class="btn primary" onclick="openAssignmentModal()">＋ Шинэ даалгавар</button></div>${rows?.length?rows.map(a=>{const fs=by.get(a.id)||[];return `<div class="notice"><b>${tpEsc(a.subject)} · ${tpEsc(a.title)}</b><p>${a.description?tpEsc(a.description)+' · ':''}${a.due_at?'Дуусах: '+tpFmt(a.due_at):'Хугацаагүй'}</p>${fs.length?`<div class="schoolActions">${fs.map(f=>`<button class="ghost" onclick="tpOpenFile('${f.file_path.replaceAll("'","\\'")}')">${tpFileIcon(f.mime_type)} ${tpEsc(f.file_name)}</button>`).join('')}</div>`:'<span class="muted">Хавсралтгүй</span>'}</div>`}).join(''):'<div class="empty">Даалгавар алга.</div>'}</div>`)}

async function tpRenderAttendance(){await tpContext();await loadTeacherDashboard();const map=new Map((teacherData.attendance||[]).map(a=>[a.student_id,a.status]));tpLayout('Ирц','Өнөөдрийн ирцийг хурдан бүртгэнэ.',`<div class="card full"><div class="sectionTitle"><h3>${tpEsc(teacherData.cls?.name||'Анги')}</h3><button class="btn primary" onclick="openAttendanceModal()">✓ Ирц бүртгэх</button></div>${teacherData.students?.length?teacherData.students.map(s=>`<div class="row"><b>${tpEsc(s.full_name)}</b><span class="pill">${({present:'Ирсэн',absent:'Тасалсан',late:'Хоцорсон',excused:'Чөлөөтэй'})[map.get(s.id)]||'Бүртгээгүй'}</span></div>`).join(''):'<div class="empty">Сурагч алга.</div>'}</div>`)}

async function tpRenderClass(){const c=await tpContext();tpLayout('Манай анги','Сурагчдаа нэмээд, сурагч бүрийн эцэг эхийг урьна.',`<div class="card narrow"><h3>Сурагч нэмэх</h3><label>Сурагчийн нэр</label><input id="tpStudentName"><label>Код</label><input id="tpStudentCode" placeholder="ST-001"><label>Төрсөн огноо</label><input id="tpStudentBirth" type="date"><button class="btn primary tpFull" onclick="tpAddStudent()">＋ Нэмэх</button><div id="tpStudentStatus" class="status"></div></div><div class="card wide"><h3>${tpEsc(c.class?.name||'Анги')}</h3>${c.students?.length?c.students.map(s=>`<div class="row"><div><b>${tpEsc(s.full_name)}</b><small> · ${tpEsc(s.student_code||'кодгүй')}</small></div><button class="ghost" onclick="tpInviteParent('${s.id}','${tpEsc(s.full_name).replaceAll("'","\\'")}')">Эцэг эх урих</button></div>`).join(''):'<div class="empty">Сурагч алга.</div>'}<div id="tpParentInviteStatus" class="status"></div></div>`)}
window.tpAddStudent=async()=>{try{const c=await tpContext(),full_name=$('tpStudentName').value.trim();if(full_name.length<2)throw new Error('Сурагчийн нэрээ оруулна уу.');showStatus($('tpStudentStatus'),'Нэмж байна…');await tpWorkflow({action:'create_student',class_id:c.class.id,full_name,student_code:$('tpStudentCode').value.trim(),birth_date:$('tpStudentBirth').value});showStatus($('tpStudentStatus'),'Сурагч нэмэгдлээ ✅','ok');await tpRenderClass()}catch(e){showStatus($('tpStudentStatus'),e.message,'err')}};
window.tpInviteParent=async(studentId,name)=>{try{showStatus($('tpParentInviteStatus'),`${name}-ийн эцэг эхийн код үүсгэж байна…`);const d=await tpWorkflow({action:'create_parent_invite',student_id:studentId});showStatus($('tpParentInviteStatus'),`✅ ${name} · Эцэг эхийн урилгын код: ${d.code}\nКод 7 хоног хүчинтэй.`,'ok')}catch(e){showStatus($('tpParentInviteStatus'),e.message,'err')}};

async function tpRenderPermission(){const c=await tpContext();const {data}=await sb.from('permissions').select('*').eq('school_id',membership.school_id).eq('class_id',c.class.id).order('created_at',{ascending:false}).limit(30);tpLayout('Зөвшөөрөл','Аялал, зураг авалт, арга хэмжээний зөвшөөрөл хүснэ.',`<div class="card narrow"><h3>Шинэ зөвшөөрөл</h3><label>Гарчиг</label><input id="tpPermTitle"><label>Тайлбар</label><textarea id="tpPermDesc" class="tpTextarea"></textarea><label>Хариу авах хугацаа</label><input id="tpPermDue" type="datetime-local"><button class="btn primary tpFull" onclick="tpSavePermission()">Илгээх</button><div id="tpPermStatus" class="status"></div></div><div class="card wide">${data?.length?data.map(p=>`<div class="notice"><b>${tpEsc(p.title)}</b><p>${tpEsc(p.description||'')}${p.due_at?' · '+tpFmt(p.due_at):''}</p></div>`).join(''):'<div class="empty">Зөвшөөрлийн хүсэлт алга.</div>'}</div>`)}
window.tpSavePermission=async()=>{try{const c=await tpContext(),title=$('tpPermTitle').value.trim();if(!title)throw new Error('Гарчиг оруулна уу.');const {error}=await sb.from('permissions').insert({school_id:membership.school_id,class_id:c.class.id,created_by:session.user.id,title,description:$('tpPermDesc').value.trim()||null,due_at:$('tpPermDue').value?new Date($('tpPermDue').value).toISOString():null});if(error)throw error;await tpRenderPermission()}catch(e){showStatus($('tpPermStatus'),e.message,'err')}};

async function tpRenderWork(){await tpContext();const {data}=await sb.from('work_documents').select('*').eq('school_id',membership.school_id).order('created_at',{ascending:false}).limit(40);tpLayout('Ажлын сан','Өөрийн болон сургуулийн материал, төлөвлөгөө, тайлангаа хадгална.',`<div class="card narrow"><h3>Файл нэмэх</h3><label>Гарчиг</label><input id="tpWorkTitle"><label>Хуваалцах</label><select id="tpWorkScope"><option value="personal">Зөвхөн би</option><option value="school">Сургуультай</option></select><label>Файл</label><input id="tpWorkFile" type="file"><button class="btn primary tpFull" onclick="tpUploadWork()">Байршуулах</button><div id="tpWorkStatus" class="status"></div></div><div class="card wide">${data?.length?data.map(d=>`<div class="row"><div><b>${tpEsc(d.title)}</b><small> · ${tpEsc(d.scope)} · ${tpEsc(d.file_name||'файлгүй')}</small></div>${d.file_path?`<button class="ghost" onclick="tpOpenFile('${d.file_path.replaceAll("'","\\'")}','work-library')">Нээх</button>`:''}</div>`).join(''):'<div class="empty">Ажлын сан хоосон.</div>'}</div>`)}
window.tpUploadWork=async()=>{try{const f=$('tpWorkFile').files?.[0],title=$('tpWorkTitle').value.trim();if(!f||!title)throw new Error('Гарчиг болон файл сонгоно уу.');if(f.size>20*1024*1024)throw new Error('Файл 20MB-аас их байна.');showStatus($('tpWorkStatus'),'Байршуулж байна…');const safe=f.name.replace(/[^a-zA-Z0-9._-]+/g,'_'),path=`${membership.school_id}/${session.user.id}/${Date.now()}_${safe}`;const {error:up}=await sb.storage.from('work-library').upload(path,f,{contentType:f.type||'application/octet-stream'});if(up)throw up;const {error}=await sb.from('work_documents').insert({school_id:membership.school_id,owner_user_id:session.user.id,category:'file',scope:$('tpWorkScope').value,title,file_path:path,file_name:f.name,mime_type:f.type||null,file_size:f.size});if(error)throw error;await tpRenderWork()}catch(e){showStatus($('tpWorkStatus'),e.message,'err')}};

async function tpRenderObservation(){const c=await tpContext();const {data}=await sb.from('student_observations').select('*').eq('school_id',membership.school_id).eq('class_id',c.class.id).order('observed_at',{ascending:false}).limit(50);tpLayout('Ажиглалт','Сурагчийн ахиц, оролцоо, дэмжлэгийн хэрэгцээг тэмдэглэнэ.',`<div class="card narrow"><h3>Ажиглалт нэмэх</h3><label>Сурагч</label><select id="tpObsStudent">${c.students.map(s=>`<option value="${s.id}">${tpEsc(s.full_name)}</option>`).join('')}</select><label>Хичээл</label><input id="tpObsSubject" value="Бусад"><label>Төрөл</label><select id="tpObsCategory"><option value="progress">Ахиц</option><option value="participation">Оролцоо</option><option value="focus">Анхаарал</option><option value="teamwork">Багаар ажиллах</option><option value="support_needed">Дэмжлэг хэрэгтэй</option><option value="other">Бусад</option></select><label>Төлөв</label><select id="tpObsStatus"><option value="good_progress">Сайн ахиц</option><option value="watch">Ажиглах</option><option value="support_needed">Дэмжлэг хэрэгтэй</option></select><label>Тэмдэглэл</label><textarea id="tpObsNote" class="tpTextarea"></textarea><label>Дараагийн алхам</label><input id="tpObsNext"><label>Харагдах байдал</label><select id="tpObsVisibility"><option value="private">Зөвхөн багш</option><option value="shared_with_parent">Эцэг эхтэй хуваалцах</option></select><button class="btn primary tpFull" onclick="tpSaveObservation()">Хадгалах</button><div id="tpObsStatusBox" class="status"></div></div><div class="card wide">${data?.length?data.map(o=>`<div class="notice"><b>${tpEsc(c.students.find(s=>s.id===o.student_id)?.full_name||'Сурагч')} · ${tpEsc(o.subject)}</b><p>${tpEsc(o.note)}${o.next_step?' · Дараагийн алхам: '+tpEsc(o.next_step):''}</p><span class="pill">${o.visibility==='shared_with_parent'?'Эцэг эхтэй хуваалцсан':'Private'}</span></div>`).join(''):'<div class="empty">Ажиглалт алга.</div>'}</div>`)}
window.tpSaveObservation=async()=>{try{const c=await tpContext(),note=$('tpObsNote').value.trim();if(note.length<2)throw new Error('Тэмдэглэлээ оруулна уу.');const {error}=await sb.from('student_observations').insert({school_id:membership.school_id,class_id:c.class.id,student_id:$('tpObsStudent').value,subject:$('tpObsSubject').value.trim()||'Бусад',category:$('tpObsCategory').value,status:$('tpObsStatus').value,note,visibility:$('tpObsVisibility').value,next_step:$('tpObsNext').value.trim()||null,created_by:session.user.id});if(error)throw error;await tpRenderObservation()}catch(e){showStatus($('tpObsStatusBox'),e.message,'err')}};

async function tpRenderMonthly(){const c=await tpContext();const {data}=await sb.from('observation_monthly_summaries').select('*').eq('school_id',membership.school_id).in('student_id',c.students.map(s=>s.id)).order('month_start',{ascending:false}).limit(30);const month=new Date().toISOString().slice(0,7)+'-01';tpLayout('Сарын тайлан','Ажиглалтаас сарын нэгтгэл гаргана.',`<div class="card narrow"><h3>Тайлан үүсгэх</h3><label>Сурагч</label><select id="tpSumStudent">${c.students.map(s=>`<option value="${s.id}">${tpEsc(s.full_name)}</option>`).join('')}</select><label>Сар</label><input id="tpSumMonth" type="month" value="${month.slice(0,7)}"><button class="btn primary tpFull" onclick="tpGenerateSummary()">✨ Сарын нэгтгэл гаргах</button><div id="tpSumStatus" class="status"></div></div><div class="card wide">${data?.length?data.map(s=>`<div class="notice"><b>${tpEsc(c.students.find(x=>x.id===s.student_id)?.full_name||'Сурагч')} · ${tpEsc(s.month_start)}</b><p>${tpEsc(s.summary_text||'')}</p>${s.support_plan?`<p><b>Дэмжлэг:</b> ${tpEsc(s.support_plan)}</p>`:''}<span class="pill">${s.shared_with_parent?'Хуваалцсан':'Private'}</span></div>`).join(''):'<div class="empty">Сарын тайлан алга.</div>'}</div>`)}
window.tpGenerateSummary=async()=>{try{const student_id=$('tpSumStudent').value,month_start=$('tpSumMonth').value+'-01';showStatus($('tpSumStatus'),'Нэгтгэл гаргаж байна…');const {data,error}=await sb.functions.invoke('schoollink-observation-summary',{body:{student_id,month_start}});if(error)throw error;if(data?.error)throw new Error(data.error);showStatus($('tpSumStatus'),'Тайлан бэлэн ✅','ok');await tpRenderMonthly()}catch(e){showStatus($('tpSumStatus'),e.message,'err')}};

async function tpRenderChat(){const c=await tpContext();const list=await tpChat({action:'list'}),threads=list.threads||[];const rows=c.students.map(s=>{const t=threads.find(x=>x.student_id===s.id||x.student_name===s.full_name);return `<button class="shChatRow" onclick="${t?`tpLoadMessages('${t.id}')`:`tpStartChat('${s.id}')`}"><span class="shChatAvatar">💬</span><span><b>${tpEsc(s.full_name)}</b><small>${t?'Яриаг нээх':'Шинэ чат эхлүүлэх'}</small></span><span class="shChatGo">›</span></button>`}).join('');tpLayout('Чат','Эцэг эхтэй хийсэн бүх яриа нэг жагсаалтад байна.',`<div class="card full"><div class="sectionTitle"><h3>Харилцан яриа</h3><span class="pill">${threads.length} чат</span></div><div id="tpChatNotice" class="status"></div><div id="tpThreadList" class="shChatList">${rows||'<div class="empty">Эхлээд ангидаа сурагч нэмнэ үү.</div>'}</div><div id="tpChatBox" class="hidden"><div class="shChatTop"><b>Мессеж</b><button type="button" class="ghost" onclick="tpCloseChat()">Хаах ×</button></div><div id="tpMessages" class="chatBox"></div><div class="schoolActions"><input id="tpMessageInput" placeholder="Мессеж бичих…" style="flex:1"><select id="tpMsgPriority" style="max-width:150px"><option value="normal">Энгийн</option><option value="needs_reply">Хариу хэрэгтэй</option><option value="urgent">Яаралтай</option></select><button class="btn primary" onclick="tpSendMessage()">Илгээх</button></div><div id="tpChatStatus" class="status"></div></div></div>`)}
window.tpStartChat=async studentId=>{try{const d=await tpChat({action:'start_for_student',student_id:studentId});if(d?.needs_parent){const box=$('tpChatNotice');if(box){box.className='status show err';box.innerHTML=`${tpEsc(d.error)} <button type="button" class="ghost" style="margin-left:8px" onclick="tpRenderView('Манай анги')">Эцэг эх урих</button>`;box.scrollIntoView({behavior:'smooth',block:'nearest'})}return}await tpLoadMessages(d.conversation_id)}catch(e){showStatus($('tpChatNotice'),e.message,'err')}};
window.tpCloseChat=()=>{teacherChatId=null;$('tpChatBox')?.classList.add('hidden');$('tpThreadList')?.classList.remove('hidden')};
window.tpLoadMessages=async id=>{try{teacherChatId=id;const d=await tpChat({action:'messages',conversation_id:id});$('tpChatBox').classList.remove('hidden');$('tpThreadList')?.classList.add('hidden');$('tpMessages').innerHTML=d.messages.length?d.messages.map(m=>`<div class="chatMsg ${m.sender_id===d.user_id?'mine':''}"><b>${m.sender_id===d.user_id?'Би':'Эцэг эх'}</b><div>${tpEsc(m.body)}</div><small>${tpFmt(m.created_at)}</small></div>`).join(''):'<div class="empty">Мессеж алга.</div>';$('tpMessages').scrollTop=$('tpMessages').scrollHeight}catch(e){alert(e.message)}};
window.tpSendMessage=async()=>{try{const body=$('tpMessageInput').value.trim();if(!body)return;await tpChat({action:'send',conversation_id:teacherChatId,body,priority:$('tpMsgPriority').value});$('tpMessageInput').value='';await tpLoadMessages(teacherChatId)}catch(e){showStatus($('tpChatStatus'),e.message,'err')}};

async function tpRenderView(name){try{if(name==='Нүүр')return tpRenderHome();if(name==='Мэдээлэл')return tpRenderInfo();if(name==='Даалгавар')return tpRenderAssignments();if(name==='Ирц')return tpRenderAttendance();if(name==='Чат')return tpRenderChat();if(name==='Манай анги')return tpRenderClass();if(name==='Зөвшөөрөл')return tpRenderPermission();if(name==='Ажлын сан')return tpRenderWork();if(name==='Ажиглалт')return tpRenderObservation();if(name==='Сарын тайлан')return tpRenderMonthly()}catch(e){tpLayout(name,'',`<div class="card full"><div class="status show err">${tpEsc(e.message)}</div></div>`)}}
window.tpRenderView=tpRenderView;

function tpInit(){if(teacherProReady)return;teacherHomeTemplate=tpTeacherSection()?.innerHTML||'';tpEnsureAssignmentFiles();const style=document.createElement('style');style.textContent=`.tpTextarea{width:100%;min-height:110px;border:1px solid var(--line);border-radius:15px;padding:12px;resize:vertical;font:inherit}.tpFull{width:100%;margin-top:12px}.actionMini{border:1px solid var(--line);cursor:pointer;text-align:left}.chatBox{height:360px;overflow:auto;padding:10px;background:#f8f8fb;border-radius:18px;margin:12px 0}.chatMsg{max-width:78%;padding:10px 12px;border-radius:16px;background:#fff;border:1px solid var(--line);margin:8px 0}.chatMsg.mine{margin-left:auto;background:var(--vs)}.chatMsg small{display:block;color:var(--muted);margin-top:5px}.shChatList{display:grid;gap:10px;margin-top:12px}.shChatRow{display:flex;align-items:center;gap:12px;width:100%;padding:13px 14px;border:1px solid var(--line);border-radius:18px;background:#fff;color:inherit;text-align:left;cursor:pointer}.shChatRow:hover{border-color:#8b78fa}.shChatAvatar{width:42px;height:42px;display:grid;place-items:center;border-radius:14px;background:#f0ecff;font-size:19px}.shChatRow span:nth-child(2){display:grid;gap:3px;flex:1}.shChatRow small{color:var(--muted)}.shChatGo{color:#765ff2;font-weight:900}.shChatTop{display:flex;justify-content:space-between;align-items:center;margin-top:14px}`;document.head.appendChild(style);teacherProReady=true;tpBindNav()}

const tpPrevSetRole=setRole;setRole=function(role){tpPrevSetRole(role);if(role==='teacher'){setTimeout(()=>{tpInit();tpBindNav()},0)}};
const tpObsNav=new MutationObserver(()=>tpBindNav());if($('nav'))tpObsNav.observe($('nav'),{childList:true});
setTimeout(tpInit,0);
